 try{
    let a=b;
 }catch(err){
    console.log("Message :"+err);
 }
